# Generated by Django 5.2.14 on 2026-06-02 14:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Cím')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Település')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Irányítószám')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonszám')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail cím')),
                ('note', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
            ],
            options={
                'verbose_name': 'Ügyfél',
                'verbose_name_plural': 'Ügyfelek',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Megnevezés')),
                ('hourly_rate', models.PositiveIntegerField(help_text='Egy munkaórára eső díj forintban.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rezsióradíj (Ft/óra)')),
                ('valid_from', models.DateField(verbose_name='Érvényesség kezdete')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Érvényesség vége')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
            ],
            options={
                'verbose_name': 'Rezsióradíj',
                'verbose_name_plural': 'Rezsióradíjak',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Multiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Szorzó neve')),
                ('type', models.CharField(choices=[('difficulty', 'Nehézségi szorzó'), ('urgency', 'Sürgősségi szorzó'), ('building', 'Épület típus szorzó'), ('other', 'Egyéb szorzó')], default='other', max_length=20, verbose_name='Típus')),
                ('value', models.DecimalField(decimal_places=2, help_text='Pl. 1,25 = +25%, 0,90 = -10%', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Szorzó érték')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Szorzó',
                'verbose_name_plural': 'Szorzók',
                'ordering': ['type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Név')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Munkakategória',
                'verbose_name_plural': 'Munkakategóriák',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name_override', models.CharField(blank=True, help_text='Akkor használd, ha az ügyfél nincs az adatbázisban.', max_length=200, verbose_name='Ügyfél neve (ha nincs regisztrálva)')),
                ('travel_fee', models.PositiveIntegerField(default=0, verbose_name='Kiszállási díj (Ft)')),
                ('material_cost', models.PositiveIntegerField(default=0, verbose_name='Anyagköltség (Ft)')),
                ('discount_percent', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kedvezmény (%)')),
                ('vat_rate', models.DecimalField(decimal_places=1, default=27, help_text='Alapértelmezetten 27%', max_digits=4, verbose_name='ÁFA kulcs (%)')),
                ('subtotal_labor', models.PositiveIntegerField(default=0, verbose_name='Munkadíj (nettó)')),
                ('subtotal_material', models.PositiveIntegerField(default=0, verbose_name='Anyagköltség (nettó)')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Végösszeg (bruttó)')),
                ('note', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('status', models.CharField(choices=[('draft', 'Piszkozat'), ('sent', 'Elküldve'), ('accepted', 'Elfogadva'), ('rejected', 'Elutasítva'), ('closed', 'Lezárva')], default='draft', max_length=20, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='kalkulator.customer', verbose_name='Ügyfél')),
                ('hourly_rate', models.ForeignKey(help_text='A rezsióradíj nem törölhető, ha ajánlat hivatkozik rá!', on_delete=django.db.models.deletion.PROTECT, to='kalkulator.hourlyrate', verbose_name='Rezsióradíj')),
            ],
            options={
                'verbose_name': 'Ajánlat',
                'verbose_name_plural': 'Ajánlatok',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Munkafolyamat neve')),
                ('unit', models.CharField(choices=[('db', 'darab'), ('m', 'méter'), ('m2', 'négyzetméter'), ('km', 'kilométer'), ('óra', 'óra'), ('alkalom', 'alkalom'), ('helyiség', 'helyiség'), ('készülék', 'készülék'), ('kör', 'áramkör'), ('pont', 'pont'), ('projekt', 'projekt'), ('szerelvény', 'szerelvény'), ('csomag', 'csomag')], default='db', max_length=20, verbose_name='Egység')),
                ('base_time_hours', models.DecimalField(decimal_places=3, help_text='Egy egységre jutó munkaidő órában. Pl. 0,45 = 27 perc', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Normaidő (óra/db)')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sorrend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kalkulator.workcategory', verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'Munkafolyamat',
                'verbose_name_plural': 'Munkafolyamatok',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tétel neve')),
                ('unit', models.CharField(max_length=20, verbose_name='Egység')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Mennyiség')),
                ('base_time_hours', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Alap normaidő (óra/egység)')),
                ('multiplier_total', models.DecimalField(decimal_places=3, default=1.0, help_text='Az összes kiválasztott szorzó szorzata', max_digits=6, verbose_name='Összesített szorzó')),
                ('calculated_hours', models.DecimalField(decimal_places=3, help_text='mennyiség × alap normaidő × összesített szorzó', max_digits=8, verbose_name='Számított munkaóra')),
                ('calculated_price', models.PositiveIntegerField(help_text='számított munkaóra × rezsióradíj', verbose_name='Számított munkadíj (Ft)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sorrend')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kalkulator.estimate', verbose_name='Ajánlat')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalkulator.workitem', verbose_name='Munkafolyamat')),
            ],
            options={
                'verbose_name': 'Ajánlati tétel',
                'verbose_name_plural': 'Ajánlati tételek',
                'ordering': ['order'],
            },
        ),
    ]
